/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectIdRouteImport } from './routes/project.$id'
import { Route as CoursePreviewRouteImport } from './routes/course.preview'
import { Route as CourseIdRouteImport } from './routes/course.$id'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authAdminLoginRouteImport } from './routes/(auth)/admin-login'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedDashboardRouteRouteImport } from './routes/_authenticated/dashboard/route'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedDashboardSourcesRouteImport } from './routes/_authenticated/dashboard/sources'
import { Route as AuthenticatedDashboardOverviewRouteImport } from './routes/_authenticated/dashboard/overview'
import { Route as AuthenticatedDashboardProjectsIndexRouteImport } from './routes/_authenticated/dashboard/projects/index'
import { Route as AuthenticatedDashboardCoursesIndexRouteImport } from './routes/_authenticated/dashboard/courses/index'
import { Route as ApiAuthCallbackGithubRouteImport } from './routes/api/auth/callback/github'
import { Route as AuthenticatedDashboardProjectsIdRouteImport } from './routes/_authenticated/dashboard/projects/$id'
import { Route as AuthenticatedDashboardCoursesIdRouteImport } from './routes/_authenticated/dashboard/courses/$id'
import { Route as authAuthGithubCallbackRouteImport } from './routes/(auth)/auth.github.callback'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdRoute = ProjectIdRouteImport.update({
  id: '/project/$id',
  path: '/project/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursePreviewRoute = CoursePreviewRouteImport.update({
  id: '/course/preview',
  path: '/course/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseIdRoute = CourseIdRouteImport.update({
  id: '/course/$id',
  path: '/course/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authAdminLoginRoute = authAdminLoginRouteImport.update({
  id: '/(auth)/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardSourcesRoute =
  AuthenticatedDashboardSourcesRouteImport.update({
    id: '/sources',
    path: '/sources',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardOverviewRoute =
  AuthenticatedDashboardOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardProjectsIndexRoute =
  AuthenticatedDashboardProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardCoursesIndexRoute =
  AuthenticatedDashboardCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const ApiAuthCallbackGithubRoute = ApiAuthCallbackGithubRouteImport.update({
  id: '/api/auth/callback/github',
  path: '/api/auth/callback/github',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardProjectsIdRoute =
  AuthenticatedDashboardProjectsIdRouteImport.update({
    id: '/projects/$id',
    path: '/projects/$id',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardCoursesIdRoute =
  AuthenticatedDashboardCoursesIdRouteImport.update({
    id: '/courses/$id',
    path: '/courses/$id',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const authAuthGithubCallbackRoute = authAuthGithubCallbackRouteImport.update({
  id: '/(auth)/auth/github/callback',
  path: '/auth/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/admin-login': typeof authAdminLoginRoute
  '/otp': typeof authOtpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/course/$id': typeof CourseIdRoute
  '/course/preview': typeof CoursePreviewRoute
  '/project/$id': typeof ProjectIdRoute
  '/dashboard/overview': typeof AuthenticatedDashboardOverviewRoute
  '/dashboard/sources': typeof AuthenticatedDashboardSourcesRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/auth/github/callback': typeof authAuthGithubCallbackRoute
  '/dashboard/courses/$id': typeof AuthenticatedDashboardCoursesIdRoute
  '/dashboard/projects/$id': typeof AuthenticatedDashboardProjectsIdRoute
  '/api/auth/callback/github': typeof ApiAuthCallbackGithubRoute
  '/dashboard/courses/': typeof AuthenticatedDashboardCoursesIndexRoute
  '/dashboard/projects/': typeof AuthenticatedDashboardProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/admin-login': typeof authAdminLoginRoute
  '/otp': typeof authOtpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/course/$id': typeof CourseIdRoute
  '/course/preview': typeof CoursePreviewRoute
  '/project/$id': typeof ProjectIdRoute
  '/dashboard/overview': typeof AuthenticatedDashboardOverviewRoute
  '/dashboard/sources': typeof AuthenticatedDashboardSourcesRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/auth/github/callback': typeof authAuthGithubCallbackRoute
  '/dashboard/courses/$id': typeof AuthenticatedDashboardCoursesIdRoute
  '/dashboard/projects/$id': typeof AuthenticatedDashboardProjectsIdRoute
  '/api/auth/callback/github': typeof ApiAuthCallbackGithubRoute
  '/dashboard/courses': typeof AuthenticatedDashboardCoursesIndexRoute
  '/dashboard/projects': typeof AuthenticatedDashboardProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/admin-login': typeof authAdminLoginRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/course/$id': typeof CourseIdRoute
  '/course/preview': typeof CoursePreviewRoute
  '/project/$id': typeof ProjectIdRoute
  '/_authenticated/dashboard/overview': typeof AuthenticatedDashboardOverviewRoute
  '/_authenticated/dashboard/sources': typeof AuthenticatedDashboardSourcesRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/(auth)/auth/github/callback': typeof authAuthGithubCallbackRoute
  '/_authenticated/dashboard/courses/$id': typeof AuthenticatedDashboardCoursesIdRoute
  '/_authenticated/dashboard/projects/$id': typeof AuthenticatedDashboardProjectsIdRoute
  '/api/auth/callback/github': typeof ApiAuthCallbackGithubRoute
  '/_authenticated/dashboard/courses/': typeof AuthenticatedDashboardCoursesIndexRoute
  '/_authenticated/dashboard/projects/': typeof AuthenticatedDashboardProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/settings'
    | '/admin-login'
    | '/otp'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/course/$id'
    | '/course/preview'
    | '/project/$id'
    | '/dashboard/overview'
    | '/dashboard/sources'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/'
    | '/auth/github/callback'
    | '/dashboard/courses/$id'
    | '/dashboard/projects/$id'
    | '/api/auth/callback/github'
    | '/dashboard/courses/'
    | '/dashboard/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/admin-login'
    | '/otp'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/course/$id'
    | '/course/preview'
    | '/project/$id'
    | '/dashboard/overview'
    | '/dashboard/sources'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings'
    | '/auth/github/callback'
    | '/dashboard/courses/$id'
    | '/dashboard/projects/$id'
    | '/api/auth/callback/github'
    | '/dashboard/courses'
    | '/dashboard/projects'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/(auth)/admin-login'
    | '/(auth)/otp'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/course/$id'
    | '/course/preview'
    | '/project/$id'
    | '/_authenticated/dashboard/overview'
    | '/_authenticated/dashboard/sources'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/'
    | '/(auth)/auth/github/callback'
    | '/_authenticated/dashboard/courses/$id'
    | '/_authenticated/dashboard/projects/$id'
    | '/api/auth/callback/github'
    | '/_authenticated/dashboard/courses/'
    | '/_authenticated/dashboard/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  authAdminLoginRoute: typeof authAdminLoginRoute
  authOtpRoute: typeof authOtpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  CourseIdRoute: typeof CourseIdRoute
  CoursePreviewRoute: typeof CoursePreviewRoute
  ProjectIdRoute: typeof ProjectIdRoute
  ApiAuthCallbackGithubRoute: typeof ApiAuthCallbackGithubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$id': {
      id: '/project/$id'
      path: '/project/$id'
      fullPath: '/project/$id'
      preLoaderRoute: typeof ProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/preview': {
      id: '/course/preview'
      path: '/course/preview'
      fullPath: '/course/preview'
      preLoaderRoute: typeof CoursePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$id': {
      id: '/course/$id'
      path: '/course/$id'
      fullPath: '/course/$id'
      preLoaderRoute: typeof CourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/admin-login': {
      id: '/(auth)/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof authAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/sources': {
      id: '/_authenticated/dashboard/sources'
      path: '/sources'
      fullPath: '/dashboard/sources'
      preLoaderRoute: typeof AuthenticatedDashboardSourcesRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/overview': {
      id: '/_authenticated/dashboard/overview'
      path: '/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof AuthenticatedDashboardOverviewRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/projects/': {
      id: '/_authenticated/dashboard/projects/'
      path: '/projects'
      fullPath: '/dashboard/projects/'
      preLoaderRoute: typeof AuthenticatedDashboardProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/courses/': {
      id: '/_authenticated/dashboard/courses/'
      path: '/courses'
      fullPath: '/dashboard/courses/'
      preLoaderRoute: typeof AuthenticatedDashboardCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/api/auth/callback/github': {
      id: '/api/auth/callback/github'
      path: '/api/auth/callback/github'
      fullPath: '/api/auth/callback/github'
      preLoaderRoute: typeof ApiAuthCallbackGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/projects/$id': {
      id: '/_authenticated/dashboard/projects/$id'
      path: '/projects/$id'
      fullPath: '/dashboard/projects/$id'
      preLoaderRoute: typeof AuthenticatedDashboardProjectsIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/courses/$id': {
      id: '/_authenticated/dashboard/courses/$id'
      path: '/courses/$id'
      fullPath: '/dashboard/courses/$id'
      preLoaderRoute: typeof AuthenticatedDashboardCoursesIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/(auth)/auth/github/callback': {
      id: '/(auth)/auth/github/callback'
      path: '/auth/github/callback'
      fullPath: '/auth/github/callback'
      preLoaderRoute: typeof authAuthGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedDashboardRouteRouteChildren {
  AuthenticatedDashboardOverviewRoute: typeof AuthenticatedDashboardOverviewRoute
  AuthenticatedDashboardSourcesRoute: typeof AuthenticatedDashboardSourcesRoute
  AuthenticatedDashboardCoursesIdRoute: typeof AuthenticatedDashboardCoursesIdRoute
  AuthenticatedDashboardProjectsIdRoute: typeof AuthenticatedDashboardProjectsIdRoute
  AuthenticatedDashboardCoursesIndexRoute: typeof AuthenticatedDashboardCoursesIndexRoute
  AuthenticatedDashboardProjectsIndexRoute: typeof AuthenticatedDashboardProjectsIndexRoute
}

const AuthenticatedDashboardRouteRouteChildren: AuthenticatedDashboardRouteRouteChildren =
  {
    AuthenticatedDashboardOverviewRoute: AuthenticatedDashboardOverviewRoute,
    AuthenticatedDashboardSourcesRoute: AuthenticatedDashboardSourcesRoute,
    AuthenticatedDashboardCoursesIdRoute: AuthenticatedDashboardCoursesIdRoute,
    AuthenticatedDashboardProjectsIdRoute:
      AuthenticatedDashboardProjectsIdRoute,
    AuthenticatedDashboardCoursesIndexRoute:
      AuthenticatedDashboardCoursesIndexRoute,
    AuthenticatedDashboardProjectsIndexRoute:
      AuthenticatedDashboardProjectsIndexRoute,
  }

const AuthenticatedDashboardRouteRouteWithChildren =
  AuthenticatedDashboardRouteRoute._addFileChildren(
    AuthenticatedDashboardRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRouteRoute:
    AuthenticatedDashboardRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  authAdminLoginRoute: authAdminLoginRoute,
  authOtpRoute: authOtpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  CourseIdRoute: CourseIdRoute,
  CoursePreviewRoute: CoursePreviewRoute,
  ProjectIdRoute: ProjectIdRoute,
  ApiAuthCallbackGithubRoute: ApiAuthCallbackGithubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
